version: '3.8'
services:
  app:
    platform: linux/amd64
    build: .
    volumes:
      - .:/usr/src
      - ~/.aws:/root/.aws:ro  
      - ~/.vscode_server:/root/.vscode-server
    ports:
      - "8800:8000"
    environment:
      - STAGE=
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: mysql:8.0
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: task-track
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "33060:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

